# Example garrison game config for Arma Reforger server
# Copy to your instance config path (e.g., ~/.garrison/instances/<name>/config.yaml) and adjust as needed.

app_id: 1874900  # Arma Reforger Dedicated Server app ID

# Executable relative to install dir or absolute
executable: "ArmaReforgerServer"

# Optional working directory (relative to install dir). Many servers prefer running from install dir.
working_dir: "."

# Default ports to expose/forward (host:container or direct when running locally)
ports:
  - "2001/udp"   # Public port
  - "17777/udp"  # A2S query port
  - "19999/udp"  # RCON

# A ready-to-use command template. Placeholders: {{install_dir}}, {{app_id}}, {{name}}, {{args}}
# The -config file below should be generated via:
#   garrison reforger init-config --scenario-id "<path/to/scenario.conf>" --output ./Configs/ServerConfig.json
# and stored under the install dir (Configs/ServerConfig.json).
command_template: >-
  {{install_dir}}/ArmaReforgerServer
  -profile {{install_dir}}/profile
  -config {{install_dir}}/Configs/ServerConfig.json
  -maxFPS 120
  {{args}}

# Additional default args appended when starting (optional)
start_args: ""

# Environment variables to set for the server process (optional)
# env:
#   LD_LIBRARY_PATH: "{{install_dir}}"

# Optional log file for the server process (managed externally)
# log_file: "{{install_dir}}/garrison-server.log"
